name: master-ci

on: push


jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: false
          path: Dockerfile
          tags: newapp:latest
          load: true
        
      
      
