name: master-ci

on: 
  push:
    branches: master

permissions:
  contents: read
  packages: write
  security-events: write
  
jobs:
  build:
    runs-on: ubuntu-22.04
    environment: Develop_ACR

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set image tag
        run: |
          IMAGE_TAG="${{ github.ref_name }}-${GITHUB_SHA::7}-$(date +%Y%m%d%H%M)"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        


      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASS }}
    
      - run: |
          docker build . -t ${{ secrets.ACR_SERVER }}/myapp:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.ACR_SERVER }}/myapp:${{ env.IMAGE_TAG }}

      
      
